### ISSUE TITLE
node start.js fails with ReferenceError: window is not defined

### ISSUE THREAD

**Issue by achiku** [byteball/headless-byteball#16]
- commit: 0b26222b346b7a14860b90717fa33dcd814d6acc
- macOS 10.11.6
- node version: v9.2.1
- npm version: 5.5.1

```
$ node start.js
finished headless conf
merged app root conf from /Users/achiku/work/achiku/headless-byteball/conf.js
app dir /Users/achiku/work/achiku/headless-byteball
not using user conf: Error: Cannot find module '/Users/achiku/Library/Application Support/headless-byteball/conf.json'
app dir /Users/achiku/work/achiku/headless-byteball
path=/Users/achiku/Library/Application Support/headless-byteball/
createDatabaseIfNecessary byteball.sqlite
app dir /Users/achiku/work/achiku/headless-byteball
takeConnectionFromPool will wait for ready
stat Error: ENOENT: no such file or directory, stat '/Users/achiku/Library/Application Support/headless-byteball/byteball.sqlite'
will copy initial db
mkdir /Users/achiku/Library/Application Support: Error: EEXIST: file already exists, mkdir '/Users/achiku/Library/Application Support'
mkdir /Users/achiku/Library/Application Support/headless-byteball/: null
db is now ready
opening new db connection
opened db
db version 11, software version 16
=== will upgrade the database, it can take some time
=== db upgrade finished
-----------------------
remote access allowed from devices: DEVICE ALLOWED TO CHAT
payouts allowed to address: WHERE THE MONEY CAN BE SENT TO
-----------------------
failed to read keys, will gen
Please name this device [akmac.local]:
Device name saved to /Users/achiku/Library/Application Support/headless-byteball/conf.json, you can edit it later if you like.

keys created
will archive if exists from unit N6QadI9yg3zLxPMphfNGJcPfddW4yHPkoGMbbGZsWa0=
/Users/achiku/work/achiku/headless-byteball/node_modules/byteballcore/mail.js:8
if (!(window && window.cordova)) {
      ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/achiku/work/achiku/headless-byteball/node_modules/byteballcore/mail.js:8:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/achiku/work/achiku/headless-byteball/node_modules/byteballcore/network.js:26:37)
    at Module._compile (module.js:571:32)
[~/work/achiku/headless-byteball] (master|✔)
$ node --version
v9.2.1
```

**Comment by tonyofbyteball** [comment]
I think it was fixed by https://github.com/byteball/byteballcore/commit/894a5b4a519bd9c419e093c7ba2a58a1fdcf05b3#diff-71a51ab03639aa934f293937ab30fb20
